# Generated by Django 3.1.5 on 2021-01-24 03:44

import api_services.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_services.user')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_services.user')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_services.user')),
                ('height', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(api_services.enums.RoleChoice['SUPER_ADMIN'], 'SUPER_ADMIN'), (api_services.enums.RoleChoice['ADMIN'], 'ADMIN'), (api_services.enums.RoleChoice['PLAYER'], 'PLAYER'), (api_services.enums.RoleChoice['COACH'], 'COACH')], max_length=10),
        ),
    ]
