# Generated by Django 3.1.5 on 2021-01-24 03:56

import api_services.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_auto_20210124_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(api_services.enums.RoleChoice['SUPER_ADMIN'], 'SUPER_ADMIN'), (api_services.enums.RoleChoice['ADMIN'], 'ADMIN'), (api_services.enums.RoleChoice['PLAYER'], 'PLAYER'), (api_services.enums.RoleChoice['COACH'], 'COACH')], default=api_services.enums.RoleChoice['SUPER_ADMIN'], max_length=10),
        ),
    ]
