# Generated by Django 3.1.5 on 2021-01-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0004_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_profile',
            new_name='user',
        ),
    ]
