# Generated by Django 3.1.5 on 2021-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0005_auto_20210124_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arena', models.CharField(max_length=255)),
            ],
        ),
    ]
