# Generated by Django 3.1.5 on 2021-01-24 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0006_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='arena',
            new_name='arena_name',
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_services.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_services.team'),
        ),
    ]
