# Generated by Django 3.1.5 on 2021-01-24 09:28

import api_services.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0009_tournament_tournamentround'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='api_services.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='api_services.team')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='NBA', max_length=255),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='name',
            field=models.CharField(choices=[(api_services.enums.TournamentRoundChoice['FIRST_ROUND'], 'FIRST_ROUND'), (api_services.enums.TournamentRoundChoice['QUARTER_FINALS'], 'ADMIN'), (api_services.enums.TournamentRoundChoice['SEMI_FINALS'], 'SEMI_FINALS'), (api_services.enums.TournamentRoundChoice['FINALS'], 'FINALS')], default=api_services.enums.TournamentRoundChoice['FIRST_ROUND'], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_services.tournament'),
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_services.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_services.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_services.tournamentround'),
        ),
    ]
