# Generated by Django 3.1.5 on 2021-01-24 15:31

import api_services.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0010_auto_20210124_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=enumfields.fields.EnumField(enum=api_services.enums.RoleChoice, max_length=10),
        ),
    ]
