# Generated by Django 3.1.5 on 2021-01-24 15:43

import api_services.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0012_auto_20210124_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentround',
            name='name',
            field=enumfields.fields.EnumField(enum=api_services.enums.TournamentRoundChoice, max_length=20),
        ),
    ]
