# Generated by Django 3.1.5 on 2021-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0013_auto_20210124_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
