# Generated by Django 3.1.5 on 2021-01-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0014_auto_20210124_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tournamentround',
            options={'ordering': ['id']},
        ),
    ]
